### ISSUE TITLE
Suggestions for alternative names

### ISSUE THREAD

**Issue by pronoiac** [kadeessh/kadeessh#12]
[From a discussion on Hacker News:](https://news.ycombinator.com/item?id=30832145) 
>> Given the name I'd at first figured it was an official Caddy project, but that does not seem to be the case. 
> 
> Names are hard. I did consider changing the name but couldn't find another one. Feel free to pitch names on GitHub. 

I tripped over a misreading, and I'll offer a variant of what I saw: 
caddysshack

**Comment by mohammed90** [comment]
I've posted a [Twitter poll](https://twitter.com/MohammedSahaf/status/1544734901852934146). Your suggestion has received a few likes already. I'll most likely adopt the name, unless the majority decides otherwise 🙂

**Comment by stappersg** [comment]
(This comment was written to `https://github.com/kadeessh/kadeessh/issues/12` (note the name) )

Did the rename happen?  I think it did.

![image](https://github.com/kadeessh/kadeessh/assets/35434094/ef057d3c-7890-43e6-9e3e-475ffa1541ce)


For which reason is this issue still open?

**Comment by mohammed90** [comment]
I still need to change it on the caddyserver.com website, so I'm keeping it as a reminder.

**Comment by mohammed90** [comment]
Done!

**Comment by stappersg** [comment]
On Mon, May 15, 2023 at 02:56:39PM -0700, Mohammed Al Sahaf wrote:
> Done!

:ok_hand:
