### ISSUE TITLE
Tunnel ssh over https / multiplex both https web site serving and ssh connections

### ISSUE THREAD

**Issue by timkgh** [kadeessh/kadeessh#17]
It would be really useful if it could tunnel SSH traffic over HTTPS. Some very restrictive firewalls do deep traffic inspection and block SSH even if you try to have the server listen on port 443 but they allow true HTTPS traffic on 443. We need an HTTPS and SSH-over-HTTPS multiplexer so you can serve a web site and also tunnel SSH traffic at some URL.

Something like this, so I don't have to run Apache too:
https://hacktr.org/blog/2020/01/01/ssh-tunneling-over-https/

**Comment by mholt** [comment]
@timkgh You should be able to do this with https://github.com/mholt/caddy-l4.

Simply set up a `tls` handler to terminate TLS, then use the `proxy` handler to forward the SSH packets.
